name: .NET Core build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-16.04, windows-2019 ]
        dotnet: [ 3.1.301 ]
        node: [ 12 ]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dotnet tools
        run: dotnet tool restore

      - name: Install C# dependencies
        run: dotnet restore

      - name: Run C# build
        run: dotnet build --configuration Release --no-restore

      - name: Run C# tests
        run: dotnet test --no-restore --verbosity normal
        working-directory: ./DigitalIcebreakers/DigitalIcebreakers.Test

      - name: Front-end tests
        run: npm run test-ci
        working-directory: ./DigitalIcebreakers/ClientApp